config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'movies#index'
  get 'users/new'   => 'users#new', as: :new_user
  post 'users'      => 'users#create'
  get '/login'      => 'sessions#new'
  post '/login'     => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  get 'movies/:id'  => 'movies#show', as: :movies
  get 'bookings'    => 'users#booking', as: :bookings
  post 'bookings/:id/cancel'    => 'users#cancel_booking', as: :cancel_bookings
  post 'book/:screening_id' => 'users#book', as: :book
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :screening
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :screenings
  has_many :theatres, -> { distinct }, through: :screenings
end

app/models/screening.rb
class Screening < ApplicationRecord
  has_many :bookings

  belongs_to :movie
  belongs_to :theatre

  def start_time
    start_at.strftime("%H:%M")
  end

  def booked? user_id
    bookings.where(user_id: user_id).first.present?
  end

  def in_the_past?
    current_time = Time.now
    start_at - start_at.midnight < current_time - current_time.midnight
  end

  def seat_available
    theatre.capacity - bookings.count
  end

  def seat_available?
    seat_available > 0
  end

  def availability_formatted
    "#{seat_available} / #{theatre.capacity} seats"
  end
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :screenings
end

app/models/user.rb
class User < ApplicationRecord
  enum gender: {
    undisclosed: 0,
    female: 1,
    male: 2
  }

  has_many :bookings

  has_secure_password

  validates :email,    presence: true,uniqueness: true,format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
  validates :password, presence: true,length: { minimum: 8 },on: :create
  validates :password, length: { minimum: 8 },allow_blank: true,on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.order(created_at: :desc)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
    user = User.find_by(email: params[:login][:email].downcase)

    # Verify user exists in db and run has_secure_password's .authenticate()
    # method to see if the password submitted on the login form was correct:
    if user && user.authenticate(params[:login][:password])
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to bookings_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    # delete the saved user_id key/value from the cookie:
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.email.downcase!

    if @user.save
      session[:user_id] = @user.id.to_s
      flash[:notice] = "Account created successfully!"
      redirect_to bookings_path
    else
      flash.now.alert = "Oops, couldn't create account."
      render :new
    end
  end

  def booking
    @bookings = current_user.bookings.order(created_at: :desc)
  end

  def book
    current_user.bookings.create(screening_id: params[:screening_id])
    redirect_to bookings_path
  end

  def cancel_booking
    current_user.bookings.find_by(id: params[:id]).delete
    redirect_to bookings_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.slim
- if showtime.booked?(current_user.id)
  = link_to "Cancel", booking_cancel_path(showtime), method: :post
- else

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  div.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      - if current_user
        li.nav-item.active
          = link_to 'Home', root_path, class: 'nav-link'
        li.nav-item
          = link_to 'Booking', bookings_path, class: 'nav-link'
        li.nav-item
          = link_to 'Logout', logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item.active
          = link_to 'Home', root_path, class: 'nav-link'
        li.nav-item
          = link_to 'Login', login_path, class: 'nav-link'
        li.nav-item
          = link_to 'Register', new_user_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title MovieBooking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'

  body
    = render "layouts/navbar"

    .container.mt-4
      = notice if notice
      = alert if alert
      = yield

app/views/movies/index.html.slim
.row.justify-content-md-center
  .col-sm-4
    - if @movies
        ul.list-group.list-group-flush
          - @movies.each do |movie|
            li.list-group-item.text-center
              h4.text-right
                = movie.name
              .small.text-right
                = link_to 'more >>', movies_path(movie)
    - else
        p No movies yet.

app/views/movies/show.html.slim
.text-center
  h3.display-3
    = @movie.name

  .row.justify-content-md-center
    - @movie.theatres.each do |theatre|
      .col-sm-12.mb-1
        h5
          = theatre.name
      - theatre.screenings.where(movie_id: @movie.id).each do |screening|
        .col-sm-4.mb-5
          .card
            .card-body
              h5.card-title
                = screening.start_time
              p
                = number_to_currency(screening.price, unit: "Rp ", precision: 0, delimiter: ".")
                = " - "
                = screening.availability_formatted

              = link_to "Book", book_path(screening), method: :post, class: 'btn btn-primary' if current_user

app/views/users/booking.html.slim
- if @bookings.empty?
  | No bookings yet.
- else
  - @bookings.each do |booking|
    h3 = booking.screening.movie.name
    p
      = booking.screening.theatre.name
      = " - "
      = booking.screening.start_time
      - if !booking.screening.in_the_past?
        = " | "
        = link_to "Cancel", cancel_bookings_path(booking), method: :post
    hr

app/views/users/new.html.slim
h1 Sign Up
= form_for @user do |f|
  div.form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  div.form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
  div.form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'
  div.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', autofocus: true
  div.form-group
    = f.label :gender
    = select_tag :gender, options_for_select(User.genders), class: 'form-control'

  div.form-group
    = f.submit "Register", class: 'btn btn-primary'